name: Python CI and Publish to PyPI

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      run_publish:
        description: 'Set to true to run the publish job'
        required: false
        default: 'false'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - name: Install Python 3.12
        run: uv python install 3.12
      - name: Sync and Install Dependencies
        run: uv sync --all-extras --dev
      - name: Run Tests
        run: uv run pytest

  publish:
    needs: test
    if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run_publish == 'true')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - name: Install Python 3.12
        run: uv python install 3.12
      - name: Sync and Install Dependencies
        run: uv sync --all-extras
      - name: Install Twine
        run: uv pip install twine
      - name: Build and Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          uv build --no-sources
          uv run twine upload dist/*